{% set version = "3.10.0.0" %}

package:
  name: typing
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/typing/typing-{{ version }}.tar.gz
  sha256: 13b4ad211f54ddbf93e5901a9967b1e07720c1d1b78d596ac6a439641aa1b130

build:
  number: 0
  noarch: python
  script: echo "dummy package for python 3"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - typing

about:
  home: https://docs.python.org/3.5/library/typing.html
  license: PSF-2.0
  license_file: LICENSE
  summary: Type Hints for Python - backport for Python<3.5

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
